import { defineConfig } from "@playwright/test";
import { playwrightWorkerServer } from "./playwright-worker-server";

const externalBaseURL = process.env.PLAYWRIGHT_BASE_URL;

export default defineConfig({
  testDir: ".",
  testMatch: [
    "live-edit.spec.ts",
    "inline-markdown.spec.ts",
    "rich-blocks.spec.ts",
    "editor-tools.spec.ts",
    "ai-chat.spec.ts",
    "editor-kb-release.spec.ts",
    "context-continuity.spec.ts",
    "w03-writing.spec.ts",
    "structural-block-operations.spec.ts",
    "nested-list-blocks.spec.ts",
    "double-click-selection.spec.ts",
    "text-selection-regression.spec.ts",
    "w04-active-block.spec.ts",
    "w05-block-type-menu.spec.ts",
    "w06-writing-dark.spec.ts",
    "w07-split-edit.spec.ts",
    "w08-code.spec.ts",
    "w09-overflow-open.spec.ts",
    "w10-save-error.spec.ts",
    "w14-block-selection.spec.ts",
    "r01-reading-closed.spec.ts",
    "r02-reading-dark.spec.ts",
    "r03-reading-search.spec.ts",
    "r04-reading-outline.spec.ts",
    "r05-reading-highlights.spec.ts",
    "r06-reading-comments.spec.ts",
    "r07-reading-tools.spec.ts",
    "r08-reading-selection.spec.ts",
    "r09-inline-mermaid.spec.ts",
    "r10-graph-viewer.spec.ts",
    "r10-graph-viewer-stress.spec.ts",
    "p01-library.spec.ts",
    "p02-recent.spec.ts",
    "p03-versions.spec.ts",
    "p04-persian-corrections.spec.ts",
    "p05-document-outline.spec.ts",
    "p06-highlights.spec.ts",
    "p07-comments.spec.ts",
    "p08-command-center-results.spec.ts",
    "p09-command-center-executing.spec.ts",
    "p10-find.spec.ts",
    "p11-replace.spec.ts",
    "p12-export-formats.spec.ts",
    "p13-export-states.spec.ts",
    "p14-settings-shell.spec.ts",
    "p14-settings-general.spec.ts",
    "p14-settings-gallery.spec.ts",
    "p15-settings-appearance-editing.spec.ts",
    "p16-settings-reading.spec.ts",
    "p17-settings-files-library.spec.ts",
    "p18-settings-privacy.spec.ts",
    "p19-settings-shortcuts.spec.ts",
    "p20-backup-settings.spec.ts",
    "p20-vault-promotion.spec.ts",
    "p20-launch.spec.ts",
    "first-run-cli-install.spec.ts",
    "software-update-ui.spec.ts",
    "p21-graph-studio.spec.ts",
    "p22-formula-studio.spec.ts",
  ],
  workers: 1,
  timeout: 60_000,
  expect: { timeout: 10_000 },
  reporter: [["line"]],
  use: {
    baseURL: externalBaseURL ?? "http://127.0.0.1:3143",
    trace: "retain-on-failure",
  },
  webServer: externalBaseURL
    ? undefined
    : playwrightWorkerServer(3143, ".wrangler/live-edit.log"),
});
